data: 
  raw_path: "data/raw/carclaims.csv"
  processed_path: "data/processed/carclaims_processed.csv"
  y: "FraudFound"
  cat: ["Month", "DayOfWeek", "DayOfWeekClaimed", "MonthClaimed", "MaritalStatus", "PolicyType", "Make"]

split:
  test_size: 0.2
  random_state: 42

model:
  RF:
    params:
      random_state: 42
      class_weight: "balanced"
    param_grid:
      n_estimators: [50]
      max_depth: [8, 12, 15]
      min_samples_split: [2]
      min_samples_leaf: [5, 10]

mlflow:
  experiment_name: "fraud_detection"